### PR TITLE
[GCP FileShare Support] Implement GCP FileShare Framework

### LINKED ISSUE #1065: Fileshare support for GCP
**Issue/Feature Description:**
Add another backend GCP for Fileshare support

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Add support for basic CRUD operations

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by himanshuvar**
**What type of PR is this?**
> /kind new feature

**What this PR does / why we need it**: FileShare Driver FrameWork support for GCP Cloud Backend
 and handling GCP Authentication mechanism for File Share APIs. It also includes the Encrypter/Decrypter for GCP credentials for securing GCP credentials in enrypted format.
**Which issue(s) this PR fixes**:
 Fixes #1065 #1074 #1075 #1086 #1087 

**Test Report Added?**:
> /kind TESTED

**Test Report**:

**Special notes for your reviewer**:

### CODE REVIEW

File: api/pkg/utils/cryptography/aes.go [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+	"io"
+)
+
+type AES struct{}
+
+func NewAES() *AES {
+	return &AES{}
+}
+
+func (*AES) Encrypter(password string, key []byte) (string, error) {
```
Comment (kumarashit) [inline api/pkg/utils/cryptography/aes.go:32]: There are already code for AES Encryption and Decryption at few places mostly in Object storage. Is that not re-usable?

File: docker-compose.yml [hunk 2]
```diff
@@ -96,6 +96,12 @@ services:
     environment:
       - MICRO_REGISTRY=mdns
       - DB_HOST=datastore:27017
+      - OS_AUTH_AUTHSTRATEGY=keystone
```
Comment (kumarashit) [inline docker-compose.yml:99]: Why is this required?

File: api/pkg/utils/cryptography/aes.go (hunk 1 above)
Comment (himanshuvar) [reply api/pkg/utils/cryptography/aes.go:32]: Yes, I have referenced the code already exists. But could able to use that because of the hard-coded interfaces. May be We need to refactor the framework to make it available as Utility for all SODA projects.

File: docker-compose.yml (hunk 2 above)
Comment (himanshuvar) [reply docker-compose.yml:99]: This is required to call our identity service to retrieve the SK for GCP credentials decryption

File: api/pkg/utils/cryptography/aes.go (hunk 1 above)
Comment (kumarashit) [reply api/pkg/utils/cryptography/aes.go:32]: Ok. This similar code is at multiple places and this is not good for maintainability

File: docker-compose.yml (hunk 2 above)
Comment (kumarashit) [reply docker-compose.yml:99]: Ok

File: api/pkg/utils/cryptography/aes.go (hunk 1 above)
Comment (himanshuvar) [reply api/pkg/utils/cryptography/aes.go:32]: Yes, There are several codes in SODA similar to this which are redundant and is not good for maintainability.
I think this code is much better than the existing code in terms of flexibility of interface and readability. You can consider this point.

Comment (kumarashit) [reply api/pkg/utils/cryptography/aes.go:32]: Ok

**Review by kumarashit — APPROVED** [review]
LGTM

**Review by skdwriting — APPROVED** [review]
LGTM

**Review by skdwriting — APPROVED** [review]
LGTM
