### PR TITLE
 CRUD API for tiering

### LINKED ISSUE #1259: Bucket Tier[POST]: API to Create tier policy
**Issue/Feature Description:**
 As a admin, I want to create tier policy. That tier can be used by user during bucket creation.

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by vineela1999**
**What type of PR is this?**
kind new feature

**What this PR does / why we need it**:
This PR contains Create,Update,List,Get and Delete tier API for sample tier

**Which issue(s) this PR fixes**:
Fixes 
#1259 
#1260
#1261
#1262

**Test Report Added?**:
kind TESTED

**Test Report**:

**Create Tier**:
Screenshot from 2021-06-09 22-04-37

**Update Tier:**
Screenshot from 2021-06-09 22-06-20

**List Tiers:**
Screenshot from 2021-06-09 22-06-37

**Get tier:**
Screenshot from 2021-06-09 22-06-53

**Delete Tier:**
Screenshot from 2021-06-09 22-08-02

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by PravinRanjan10** [comment]
Please do the following:
1. run make goimports to format your all file in go standard.
2. Update the "What type of PR is this?" section 
3. Add the all Crud issues no in the section "Which issue(s) this PR fixes:"

File: backend/pkg/model/model.go [hunk 1]
```diff
@@ -30,3 +30,11 @@ type Backend struct {
 	Access     string        `json:"access,omitempty" bson:"access,omitempty"`
 	Security   string        `json:"security,omitempty" bson:"security,omitempty"`
 }
+
+type Tier struct {
+	Id        bson.ObjectId `json:"id,omitempty" bson:"_id,omitempty"`
+	TenantId  string        `json:"tenantId,omitempty" bson:"tenantId,omitempty"`
+	UserId    string        `json:"userId,omitempty" bson:"userId,omitempty"`
+	Name      string        `json:"name,omitempty" bson:"name,omitempty"`
+	BackendId string        `json:"type,omitempty" bson:"type,omitempty"`
```
Comment (PravinRanjan10) [inline backend/pkg/model/model.go:39]: Instead of BackendId, make it Backends and data type would be list.
Ex: Backends []string

Accordingly make changes to all the places

File: api/pkg/backend/service.go [hunk 2]
```diff
@@ -447,3 +446,133 @@ func (s *APIService) listStorageType(ctx context.Context, request *restful.Reque
 	storageTypes, err := s.backendClient.ListType(ctx, listTypeRequest)
 	return storageTypes, err
 }
+
+func (s *APIService) CreateTier(request *restful.Request, response *restful.Response) {
```
Comment (PravinRanjan10) [inline api/pkg/backend/service.go:450]: Somewthere it should validate, the backends whether they really exists or not. Before Creating or adding to DB.

File: api/pkg/backend/service.go [hunk 3]
```diff
@@ -447,3 +446,133 @@ func (s *APIService) listStorageType(ctx context.Context, request *restful.Reque
...
+		log.Errorf("failed to read request body: %v\n", err)
+		response.WriteError(http.StatusInternalServerError, err)
+		return
+	}
+	ctx := common.InitCtxWithAuthInfo(request)
+	actx := request.Attribute(c.KContext).(*c.Context)
+	tier.TenantId = actx.TenantId
+	tier.UserId = actx.UserId
+
+	res, err := s.backendClient.CreateTier(ctx, &backend.CreateTierRequest{Tier: tier})
```
Comment (PravinRanjan10) [inline api/pkg/backend/service.go:464]: As mentioned in some other comment, it should handle list of backends in a single tier. Please check logic again.

File: api/pkg/backend/service.go [hunk 4]
```diff
@@ -447,3 +446,133 @@ func (s *APIService) listStorageType(ctx context.Context, request *restful.Reque
...
+
+	sortKeys, sortDirs, err := common.GetSortParam(request)
+	if err != nil {
+		log.Errorf("get sort parameters failed: %v\n", err)
+		response.WriteError(http.StatusInternalServerError, err)
+		return
+	}
+	listTierRequest.SortKeys = sortKeys
+	listTierRequest.SortDirs = sortDirs
+	log.Debug("***before list tier****")
```
Comment (PravinRanjan10) [inline api/pkg/backend/service.go:542]: Remove all debug messages, if any there in other place also.

**Review by PravinRanjan10 — CHANGES_REQUESTED** [review]

File: backend/proto/backend.proto [hunk 5]
```diff
@@ -87,3 +93,56 @@ message TypeDetail {
...
+	string id = 1;
+}
+
+message DeleteTierResponse {
+}
+
+message Tier {
+	string id = 1;
+	string tenantId = 2;
+	string userId = 3;
```
Comment (PravinRanjan10) [inline backend/proto/backend.proto:143]: reove the userId from Tier.

**Comment by anvithks** [comment]
@vineela1999 @PravinRanjan10 In case of update tiers, can the admin remove any previously added backends from the tier if user has already created a bucket using that tier and is assigned to that backend.
For ex: Tier A has Backend X and Backend Y.
User creates bucket with Tier A that gets created in Backend Y.
Admin updates the Tier A and removes the Backend Y from the list of backends. 

Will this action be allowed?

**Comment by PravinRanjan10** [comment]
> @vineela1999 @PravinRanjan10 In case of update tiers, can the admin remove any previously added backends from the tier if user has already created a bucket using that tier and is assigned to that backend.
> For ex: Tier A has Backend X and Backend Y.
> User creates bucket with Tier A that gets created in Backend Y.
> Admin updates the Tier A and removes the Backend Y from the list of backends.
> 
> Will this action be allowed?

No. This action will not be allowed. Update(removing backend) only possible if there is no bucket associated with that backend.

**Comment by anvithks** [comment]
@PravinRanjan10 What if a particular backend is upgraded / downgraded ?

For ex: Tier A has Backend X and Backend Y.
User creates bucket P with Tier A that gets created in Backend Y.
Backend Y is costing is now changed and company policy wants it to be changed to Tier D.
How will the admin handle this situation?

**Comment by kumarashit** [comment]
@vineela1999 Where is the associated issue? What is the requirement and design changes considered for this? Where is the API spec defined?

File: backend/pkg/model/model.go (hunk 1 above)
Comment (vineela1999) [reply backend/pkg/model/model.go]: changed

File: api/pkg/backend/service.go (hunk 2 above)
Comment (vineela1999) [reply api/pkg/backend/service.go:451]: done

File: api/pkg/backend/service.go (hunk 3 above)
Comment (vineela1999) [reply api/pkg/backend/service.go:475]: done

File: api/pkg/backend/service.go (hunk 4 above)
Comment (vineela1999) [reply api/pkg/backend/service.go]: done

File: backend/proto/backend.proto (hunk 5 above)
Comment (vineela1999) [reply backend/proto/backend.proto]: done

File: api/pkg/backend/router.go [hunk 6]
```diff
@@ -35,4 +35,18 @@ func RegisterRouter(ws *restful.WebService) {
...
+
+	ws.Route(ws.GET("/{tenantId}/tiers/{id}").To(handler.GetTier)).
+		Doc("Show tier details")
+	ws.Route(ws.GET("/{tenantId}/tiers").To(handler.ListTiers)).
+		Doc("list tiers")
+	ws.Route(ws.POST("/{tenantId}/tiers").To(handler.CreateTier)).
+		Doc("Create tier")
+	ws.Route(ws.PUT("/{tenantId}/tiers/{id}").To(handler.UpdateTier)).
+		Doc("Update tier")
+	ws.Route(ws.DELETE("/{tenantId}/tiers/{id}/{backendId}").To(handler.DeleteTierBackend)).
```
Comment (PravinRanjan10) [inline api/pkg/backend/router.go:47]: why there is new API for deleting. It should be added in UpdateTier only

**Review by PravinRanjan10 — CHANGES_REQUESTED** [review]

File: api/pkg/backend/service.go (hunk 3 above)
Comment (PravinRanjan10) [reply api/pkg/backend/service.go:475]: What happens if, multiple backends are added, and 1st backnd itself doesn't exist. It won't check for other backends,

File: api/pkg/backend/service.go [hunk 7]
```diff
@@ -447,3 +446,172 @@ func (s *APIService) listStorageType(ctx context.Context, request *restful.Reque
...
+	updateTierRequest := backend.UpdateTierRequest{Id: id}
+	err := request.ReadEntity(&updateTierRequest)
+	if err != nil {
+		log.Errorf("failed to read request body: %v\n", err)
+		response.WriteError(http.StatusInternalServerError, err)
+		return
+	}
+	ctx := common.InitCtxWithAuthInfo(request)
+
+	//validation of backendId
```
Comment (PravinRanjan10) [inline api/pkg/backend/service.go:500]: multiple backends can not be updated at a time??

File: api/pkg/backend/service.go [hunk 8]
```diff
@@ -447,3 +446,172 @@ func (s *APIService) listStorageType(ctx context.Context, request *restful.Reque
...
+		return
+	}
+
+	log.Info("List tiers successfully.")
+	response.WriteEntity(res)
+	return
+}
+
+//backend can be deleted
+func (s *APIService) DeleteTierBackend(request *restful.Request, response *restful.Response) {
```
Comment (PravinRanjan10) [inline api/pkg/backend/service.go:571]: I think this method is not required.

File: backend/pkg/db/drivers/mongo/mongo.go [hunk 9]
```diff
@@ -182,6 +182,116 @@ func (repo *mongoRepository) ListBackend(ctx context.Context, limit, offset int,
...
+
+	err := UpdateContextFilter(ctx, m)
+	if err != nil {
+		return err
+	}
+
+	return session.DB(defaultDBName).C(defaultTierCollection).Remove(m)
+}
+
+func (repo *mongoRepository) DeleteTierBackend(ctx context.Context, id string, backendId string) error {
```
Comment (PravinRanjan10) [inline backend/pkg/db/drivers/mongo/mongo.go:218]: This method is not required

**Review by PravinRanjan10 — CHANGES_REQUESTED** [review]

File: api/pkg/backend/service.go (hunk 3 above)
Comment (vineela1999) [reply api/pkg/backend/service.go:493]: added

File: api/pkg/backend/router.go (hunk 6 above)
Comment (vineela1999) [reply api/pkg/backend/router.go]: removed

File: api/pkg/backend/service.go (hunk 7 above)
Comment (vineela1999) [reply api/pkg/backend/service.go]: updated

File: api/pkg/backend/service.go (hunk 8 above)
Comment (vineela1999) [reply api/pkg/backend/service.go]: removed

File: backend/pkg/db/drivers/mongo/mongo.go (hunk 9 above)
Comment (vineela1999) [reply backend/pkg/db/drivers/mongo/mongo.go]: removed

**Review by PravinRanjan10 — CHANGES_REQUESTED** [review]

File: api/pkg/backend/service.go [hunk 10]
```diff
@@ -447,3 +446,194 @@ func (s *APIService) listStorageType(ctx context.Context, request *restful.Reque
...
+	//validation of backends
+	listBackendRequest := &backend.ListBackendRequest{}
+	result, err := s.backendClient.ListBackend(ctx, listBackendRequest)
+        if err != nil {
+                log.Errorf("failed to list backends: %v\n", err)
+                response.WriteError(http.StatusInternalServerError, err)
+                return
+        }
+
+	failBackends:=""
```
[the remark this answers is not in the document]
Comment (vineela1999) [reply api/pkg/backend/service.go]: changed

File: backend/pkg/db/drivers/mongo/mongo.go [hunk 11]
```diff
@@ -182,6 +182,103 @@ func (repo *mongoRepository) ListBackend(ctx context.Context, limit, offset int,
...
+	session := repo.session.Copy()
+	defer session.Close()
+	m := bson.M{"_id": bson.ObjectIdHex(id)}
+	ua := bson.M{"$push": bson.M{"backends": bson.M{ "$each": addBackends }}}
+	ud := bson.M{"$pullAll": bson.M{"backends": deleteBackends }}
+	err := UpdateContextFilter(ctx, m)
+	if err != nil {
+		return err
+	}
+	err = session.DB(defaultDBName).C(defaultTierCollection).Update(m, ua)
```
[the remark this answers is not in the document]
Comment (vineela1999) [reply backend/pkg/db/drivers/mongo/mongo.go]: modified

File: backend/pkg/service/service.go [hunk 12]
```diff
@@ -269,3 +268,128 @@ func (b *backendService) ListType(ctx context.Context, in *pb.ListTypeRequest, o
...
+func (b *backendService) UpdateTier(ctx context.Context, in *pb.UpdateTierRequest, out *pb.UpdateTierResponse) error {
+	log.Info("Received UpdateTier request.")
+//
+	res,err:= db.Repo.GetTier(ctx,in.Id)
+
+	//to delete backends
+	var delBackends []string
+	for _,backendId:= range res.Backends{
+		found:=false
+		for _,bcknd:= range in.DeleteBackends{
```
Comment (kumarashit) [inline backend/pkg/service/service.go:303]: Why not this validation in api service?

File: backend/pkg/service/service.go [hunk 13]
```diff
@@ -269,3 +268,128 @@ func (b *backendService) ListType(ctx context.Context, in *pb.ListTypeRequest, o
...
+				found=true
+			}
+		}
+		if found==false{
+			delBackends= append(delBackends,backendId)
+		}
+	}
+
+	//add backends to be added
+	res.Backends= delBackends
```
Comment (kumarashit) [inline backend/pkg/service/service.go:314]: Can you check if addition list and deletion list are updated properly, here?

File: api/pkg/backend/service.go [hunk 14]
```diff
@@ -447,3 +446,191 @@ func (s *APIService) listStorageType(ctx context.Context, request *restful.Reque
...
+				exists=true;
+				break;
+			}
+		}
+		if exists==false{
+		failBackends=append(failBackends,backendId)
+	}
+	}
+
+	 if len(failBackends) !=0{
```
[the remark this answers is not in the document]
Comment (PravinRanjan10) [reply api/pkg/backend/service.go:487]: The main reason for this is, at one scan, all the invalid backends can be returned. So it may help user to correct all invalid backends in one go.

File: backend/pkg/service/service.go (hunk 13 above)
Comment (vineela1999) [reply backend/pkg/service/service.go]: resolved

File: backend/pkg/service/service.go (hunk 12 above)
Comment (vineela1999) [reply backend/pkg/service/service.go]: replaced

File: api/pkg/backend/service.go [hunk 15]
```diff
@@ -447,3 +446,191 @@ func (s *APIService) listStorageType(ctx context.Context, request *restful.Reque
...
+	ctx := common.InitCtxWithAuthInfo(request)
+	res, err := s.backendClient.GetTier(ctx, &backend.GetTierRequest{Id: id})
+	if err != nil {
+		log.Errorf("failed to get tier details: %v\n", err)
+		response.WriteError(http.StatusInternalServerError, err)
+		return
+	}
+	// check whether tier is empty
+	if len(res.Tier.Backends) != 0 {
+		log.Errorf("failed to delete tier bez tier is not empty: %v\n", err)
```
[the remark this answers is not in the document]
Comment (vineela1999) [reply api/pkg/backend/service.go]: changed

File: api/pkg/backend/router.go [hunk 16]
```diff
@@ -35,4 +35,16 @@ func RegisterRouter(ws *restful.WebService) {
...
+
+	ws.Route(ws.GET("/{tenantId}/tiers/{id}").To(handler.GetTier)).
+		Doc("Show tier details")
+	ws.Route(ws.GET("/{tenantId}/tiers").To(handler.ListTiers)).
+		Doc("list tiers")
+	ws.Route(ws.POST("/{tenantId}/tiers").To(handler.CreateTier)).
+		Doc("Create tier")
+	ws.Route(ws.PUT("/{tenantId}/tiers/{id}").To(handler.UpdateTier)).
+		Doc("Update tier")
+	ws.Route(ws.DELETE("/{tenantId}/tiers/{id}").To(handler.DeleteTier)).
```
[the remark this answers is not in the document]
Comment (vineela1999) [reply api/pkg/backend/router.go:47]: not yet implemented

File: api/pkg/backend/service.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (vineela1999) [reply api/pkg/backend/service.go]: not exiting  displaying all invalid backends

File: api/pkg/backend/service.go [hunk 17]
```diff
@@ -447,3 +446,191 @@ func (s *APIService) listStorageType(ctx context.Context, request *restful.Reque
...
+                log.Errorf("failed to list backends: %v\n", err)
+                response.WriteError(http.StatusInternalServerError, err)
+                return
+        }
+
+	var failBackends []string
+	for _,backendId := range tier.Backends{
+		exists:=false
+		for _,backend:= range result.Backends{
+			if(backendId==backend.Id){
```
[the remark this answers is not in the document]
Comment (vineela1999) [reply api/pkg/backend/service.go]: yes

File: api/pkg/backend/service.go [hunk 18]
```diff
@@ -447,3 +446,191 @@ func (s *APIService) listStorageType(ctx context.Context, request *restful.Reque
...
+				exists=true;
+				break;
+			}
+		}
+		if exists==false{
+		failBackends=append(failBackends,backendId)
```
[the remark this answers is not in the document]
Comment (vineela1999) [reply api/pkg/backend/service.go]: done

**Comment by anvithks** [comment]
> @PravinRanjan10 What if a particular backend is upgraded / downgraded ?
> 
> For ex: Tier A has Backend X and Backend Y.
> User creates bucket P with Tier A that gets created in Backend Y.
> Backend Y is costing is now changed and company policy wants it to be changed to Tier D.
> How will the admin handle this situation?

@PravinRanjan10 @vineela1999 
Did you get a chance to look at this?

File: api/pkg/backend/service.go [hunk 19]
```diff
@@ -447,3 +460,342 @@ func (s *APIService) listStorageType(ctx context.Context, request *restful.Reque
 	storageTypes, err := s.backendClient.ListType(ctx, listTypeRequest)
 	return storageTypes, err
 }
+
+//tiering functions
+func (s *APIService) CreateTier(request *restful.Request, response *restful.Response) {
+	log.Info("Received request for creating tier.")
+	tier := &backend.Tier{}
+	body := ReadBody(request)
```
Comment (kumarashit) [inline api/pkg/backend/service.go:468]: why request.ReadEntity() not be used?

File: api/pkg/backend/service.go [hunk 20]
```diff
@@ -447,3 +460,342 @@ func (s *APIService) listStorageType(ctx context.Context, request *restful.Reque
...
+			log.Error(errMsg)
+			response.WriteError(http.StatusBadRequest, errors.New(errMsg))
+			return
+		}
+	}
+
+	//duplicate backends check:
+	visited := make(map[string]int, 0)
+	for _, val := range tier.Backends {
+
```
Comment (kumarashit) [inline api/pkg/backend/service.go:507]: remove blank line

File: api/pkg/backend/service.go [hunk 21]
```diff
@@ -447,3 +460,342 @@ func (s *APIService) listStorageType(ctx context.Context, request *restful.Reque
...
+		visited[val]++
+	}
+
+	var duplicates []string
+	for u, v := range visited {
```
Comment (kumarashit) [inline api/pkg/backend/service.go:512]: can these be written in the for loop at 508? simply if visited[val] > 0: duplicates = append(duplicates, val)

File: api/pkg/backend/service.go [hunk 22]
```diff
@@ -447,3 +460,342 @@ func (s *APIService) listStorageType(ctx context.Context, request *restful.Reque
...
+
+	//validation of add backends
+	listBackendRequest := &backend.ListBackendRequest{}
+	result, err := s.backendClient.ListBackend(ctx, listBackendRequest)
+	if err != nil {
+		log.Errorf("failed to list backends: %v\n", err)
+		response.WriteError(http.StatusInternalServerError, err)
+		return
+	}
+
```
Comment (kumarashit) [inline api/pkg/backend/service.go:627]: Everywhere in the code, please put more comments. Like at the start of for loop why this is being done

File: api/pkg/backend/service.go (hunk 19 above)
Comment (vineela1999) [reply api/pkg/backend/service.go:468]: to validate schema unmarshal is used instead of ReadEntity

File: api/pkg/backend/service.go (hunk 20 above)
Comment (vineela1999) [reply api/pkg/backend/service.go]: done

File: api/pkg/backend/service.go (hunk 21 above)
Comment (vineela1999) [reply api/pkg/backend/service.go]: done

File: api/pkg/backend/service.go (hunk 22 above)
Comment (vineela1999) [reply api/pkg/backend/service.go:623]: added

**Review by kumarashit — APPROVED** [review]
LGTM

**Comment by PravinRanjan10** [comment]
#1270 opened one issues to track all optomization and validation relted things

**Comment by PravinRanjan10** [comment]
LGTM

**Comment by rajat-soda** [comment]
LGTM

**Review by NajmudheenCT — APPROVED** [review]
LGTM
