### PR TITLE
Enhancement to Multi-Cloud Block Support for AWS Create/List/Get/Update/Delete

### LINKED ISSUE #962: Define Data Model i.e. Volume for Block Support
**Issue/Feature Description:**
For Block Support in Multi-Cloud, Data Models needs to be defined for Block resources like Volume.

**Why this issue to fixed / feature is needed(give scenarios or use cases):**Block Support in Multi-Cloud

**How to reproduce, in case of a bug:**
This is a feature

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by himanshuvar**
**What type of PR is this?**
> /kind new feature

**What this PR does / why we need it**:
Enhancement to Volume API support for AWS Cloud Backend. This PR is enhancement to #1033 Volume Service is enhanced for persisting data resources in DB. Also This PR have Driver Framework includes the Driver Factory Implementation for AWS Block Driver Adapter.
Design Spec: https://github.com/sodafoundation/design-specs/blob/master/specs/multicloud/Block_Storage_Service.md

**Which issue(s) this PR fixes**:

Fixes #962 #963 #977 #978 #979 #1038 #1039 #1040 #1041 #1042 #1043

**Test Report Added?**:
> /kind TESTED

**Test Report**:

The following testing is done for Voume API:

- [x] Register Backend

- [x] List Backend

- [x] Create Volume for AWS Backend

- [x] List all Volume

- [x] List Volume for AWS Backend

- [x] Get Volume

- [x] Update Volume for AWS Backend

- [x] Volume FileShare

1. Register a Backend

POST http://192.168.20.162:8089/v1/94b280022d0c4401bcf3b0ea85870519/backends
Request
```
{
  "Name": "aws-backend-block",
  "Type": "aws-block",
  "Region": "ap-south-1",
  "Access": "myAccessKey",
  "Security": "mySecretKey"
}
```
Response:
```
{
    "id": "5f3cf5592d2e8f0001c11f1f",
    "tenantId": "94b280022d0c4401bcf3b0ea85870519",
    "userId": "558057c4256545bd8a307c37464003c9",
    "name": "aws-backend-block",
    "type": "aws-block",
    "region": "ap-south-1",
    "access": "myAccessKey",
    "security": "mySecretKey"
}
```

2. Create a general purpose Volume

POST http://192.168.20.162:8089/v1/94b280022d0c4401bcf3b0ea85870519/volumes
Request:
```
{
    "name": "himanshu",
    "description": "AWS Volume",
    "backendId": "5f3cf5592d2e8f0001c11f1f",
    "availabilityZone": "ap-south-1a",
    "size": 1,
    "type": "gp2",
    "tags": [
        {
            "key": "Name",
            "value": "himanshu"
        }
    ]
}
```
Response:
```
{
    "id": "5f3cf65a5dc8d300018d8db3",
    "createdAt": "2020-08-19T15:22:26",
    "updatedAt": "2020-08-19T15:22:26",
    "name": "himanshu",
    "description": "AWS Volume",
    "tenantId": "94b280022d0c4401bcf3b0ea85870519",
    "userId": "558057c4256545bd8a307c37464003c9",
    "backendId": "5f3cf5592d2e8f0001c11f1f",
    "backend": "aws-backend-block",
    "size": 1,
    "type": "gp2",
    "region": "ap-south-1",
    "availabilityZone": "ap-south-1a",
    "status": "creating",
    "iops": 100,
    "tags": [
        {
            "key": "Name",
            "value": "himanshu"
        }
    ],
    "metadata": {
        "fields": {
            "CreationTimeAtBackend": {
                "Kind": {
                    "StringValue": "2020-08-19T09:52:26Z"
                }
            },
            "VolumeId": {
                "Kind": {
                    "StringValue": "vol-03deedaee2de0060f"
                }
            }
        }
    }
}
```

3. Create a provisioned IOPS Volume with Encryption

POST: http://192.168.20.162:8089/v1/94b280022d0c4401bcf3b0ea85870519/volumes

Request:
```
{
    "name": "ashit",
    "description": "AWS Volume",
    "backendId": "5f3cf5592d2e8f0001c11f1f",
	"availabilityZone": "ap-south-1a",
	"size": 4,
	"type": "io1",
	"iops": 100,
	"encrypted": true,
    "encryptionSettings": {
        "KmsKeyId": "<KmsKeyId>"
    },
    "tags": [
        {
            "key": "Name",
            "value": "ashit"
        }
    ]
}
```
Response:
```
{
    "id": "5f3cf6c05dc8d300018d8db4",
    "createdAt": "2020-08-19T15:24:08",
    "updatedAt": "2020-08-19T15:24:08",
    "name": "ashit",
    "description": "AWS Volume",
    "tenantId": "94b280022d0c4401bcf3b0ea85870519",
    "userId": "558057c4256545bd8a307c37464003c9",
    "backendId": "5f3cf5592d2e8f0001c11f1f",
    "backend": "aws-backend-block",
    "size": 4,
    "type": "io1",
    "region": "ap-south-1",
    "availabilityZone": "ap-south-1a",
    "status": "creating",
    "iops": 100,
    "tags": [
        {
            "key": "Name",
            "value": "ashit"
        }
    ],
    "encrypted": true,
    "encryptionSettings": {
        "KmsKeyId": "<KmsKeyId>"
    },
    "metadata": {
        "fields": {
            "CreationTimeAtBackend": {
                "Kind": {
                    "StringValue": "2020-08-19T09:54:08Z"
                }
            },
            "VolumeId": {
                "Kind": {
                    "StringValue": "vol-06a7802d1713a0504"
                }
            }
        }
    }
}
```

4. Create a Cold HDD Volume

POST: http://192.168.20.162:8089/v1/94b280022d0c4401bcf3b0ea85870519/volumes
Request:
```
{
    "name": "anvithks",
    "description": "AWS Volume",
    "backendId": "5f3cf5592d2e8f0001c11f1f",
    "availabilityZone": "ap-south-1a",
    "size": 500,
    "type": "sc1",
    "tags": [
        {
            "key": "Name",
            "value": "anvithks"
        }
    ]
}
```
Response:
```
{
    "id": "5f3cf7585dc8d300018d8db5",
    "createdAt": "2020-08-19T15:26:40",
    "updatedAt": "2020-08-19T15:26:40",
    "name": "anvithks",
    "description": "AWS Volume",
    "tenantId": "94b280022d0c4401bcf3b0ea85870519",
    "userId": "558057c4256545bd8a307c37464003c9",
    "backendId": "5f3cf5592d2e8f0001c11f1f",
    "backend": "aws-backend-block",
    "size": 500,
    "type": "sc1",
    "region": "ap-south-1",
    "availabilityZone": "ap-south-1a",
    "status": "creating",
    "tags": [
        {
            "key": "Name",
            "value": "anvithks"
        }
    ],
    "metadata": {
        "fields": {
            "CreationTimeAtBackend": {
                "Kind": {
                    "StringValue": "2020-08-19T09:56:40Z"
                }
            },
            "VolumeId": {
                "Kind": {
                    "StringValue": "vol-0322888eed5227f94"
                }
            }
        }
    }
}
```
5. Create a Throughput Optimized HDD Volume

POST: http://192.168.20.162:8089/v1/94b280022d0c4401bcf3b0ea85870519/volumes
Request:
```
{
    "name": "sanil",
    "description": "AWS Volume",
    "backendId": "5f3cf5592d2e8f0001c11f1f",
    "availabilityZone": "ap-south-1a",
    "size": 500,
    "type": "st1",
    "tags": [
        {
            "key": "Name",
            "value": "sanil"
        }
    ]
}
```
Response:
```
{
    "id": "5f3cf79f5dc8d300018d8db6",
    "createdAt": "2020-08-19T15:27:51",
    "updatedAt": "2020-08-19T15:27:51",
    "name": "sanil",
    "description": "AWS Volume",
    "tenantId": "94b280022d0c4401bcf3b0ea85870519",
    "userId": "558057c4256545bd8a307c37464003c9",
    "backendId": "5f3cf5592d2e8f0001c11f1f",
    "backend": "aws-backend-block",
    "size": 500,
    "type": "st1",
    "region": "ap-south-1",
    "availabilityZone": "ap-south-1a",
    "status": "creating",
    "tags": [
        {
            "key": "Name",
            "value": "sanil"
        }
    ],
    "metadata": {
        "fields": {
            "CreationTimeAtBackend": {
                "Kind": {
                    "StringValue": "2020-08-19T09:57:51Z"
                }
            },
            "VolumeId": {
                "Kind": {
                    "StringValue": "vol-069aa8d55f90efeee"
                }
            }
        }
    }
}
```
6. Create a Magnetic(Standard) Volume
POST: http://192.168.20.162:8089/v1/94b280022d0c4401bcf3b0ea85870519/volumes
Request:
```
{
    "name": "fannie",
    "description": "AWS Volume",
    "backendId": "5f3cf5592d2e8f0001c11f1f",
    "availabilityZone": "ap-south-1a",
    "size": 1,
    "type": "standard",
    "tags": [
        {
            "key": "Name",
            "value": "fannie"
        }
    ]
}
```
Response:
```
{
    "id": "5f3cf7d75dc8d300018d8db7",
    "createdAt": "2020-08-19T15:28:47",
    "updatedAt": "2020-08-19T15:28:47",
    "name": "fannie",
    "description": "AWS Volume",
    "tenantId": "94b280022d0c4401bcf3b0ea85870519",
    "userId": "558057c4256545bd8a307c37464003c9",
    "backendId": "5f3cf5592d2e8f0001c11f1f",
    "backend": "aws-backend-block",
    "size": 1,
    "type": "standard",
    "region": "ap-south-1",
    "availabilityZone": "ap-south-1a",
    "status": "creating",
    "tags": [
        {
            "key": "Name",
            "value": "fannie"
        }
    ],
    "metadata": {
        "fields": {
            "CreationTimeAtBackend": {
                "Kind": {
                    "StringValue": "2020-08-19T09:58:46Z"
                }
            },
            "VolumeId": {
                "Kind": {
                    "StringValue": "vol-0a4a33b0187aac057"
                }
            }
        }
    }
}
```
image

7. List Volumes

GET: http://192.168.20.162:8089/v1/94b280022d0c4401bcf3b0ea85870519/volumes
Response:
```
{
    "volumes": [
        {
            "id": "5f3cf65a5dc8d300018d8db3",
            "createdAt": "2020-08-19T15:22:26",
            "updatedAt": "2020-08-19T15:22:32",
            "name": "himanshu",
            "description": "AWS Volume",
            "tenantId": "94b280022d0c4401bcf3b0ea85870519",
            "userId": "558057c4256545bd8a307c37464003c9",
            "backendId": "5f3cf5592d2e8f0001c11f1f",
            "backend": "aws-backend-block",
            "size": 1,
            "type": "gp2",
            "region": "ap-south-1",
            "availabilityZone": "ap-south-1a",
            "status": "available",
            "iops": 100,
            "tags": [
                {
                    "key": "Name",
                    "value": "himanshu"
                }
            ],
            "metadata": {
                "fields": {
                    "CreationTimeAtBackend": {
                        "Kind": {
                            "StringValue": "2020-08-19T09:52:26.284Z"
                        }
                    },
                    "VolumeId": {
                        "Kind": {
                            "StringValue": "vol-03deedaee2de0060f"
                        }
                    }
                }
            }
        },
        {
            "id": "5f3cf6c05dc8d300018d8db4",
            "createdAt": "2020-08-19T15:24:08",
            "updatedAt": "2020-08-19T15:24:14",
            "name": "ashit",
            "description": "AWS Volume",
            "tenantId": "94b280022d0c4401bcf3b0ea85870519",
            "userId": "558057c4256545bd8a307c37464003c9",
            "backendId": "5f3cf5592d2e8f0001c11f1f",
            "backend": "aws-backend-block",
            "size": 4,
            "type": "io1",
            "region": "ap-south-1",
            "availabilityZone": "ap-south-1a",
            "status": "available",
            "iops": 100,
            "tags": [
                {
                    "key": "Name",
                    "value": "ashit"
                }
            ],
            "encrypted": true,
            "encryptionSettings": {
                "KmsKeyId": "arn:aws:kms:ap-south-1:586825186478:key/35890dfd-efa4-48fa-9900-443f31a85835"
            },
            "metadata": {
                "fields": {
                    "CreationTimeAtBackend": {
                        "Kind": {
                            "StringValue": "2020-08-19T09:54:08.349Z"
                        }
                    },
                    "VolumeId": {
                        "Kind": {
                            "StringValue": "vol-06a7802d1713a0504"
                        }
                    }
                }
            }
        },
        {
            "id": "5f3cf7585dc8d300018d8db5",
            "createdAt": "2020-08-19T15:26:40",
            "updatedAt": "2020-08-19T15:26:46",
            "name": "anvithks",
            "description": "AWS Volume",
            "tenantId": "94b280022d0c4401bcf3b0ea85870519",
            "userId": "558057c4256545bd8a307c37464003c9",
            "backendId": "5f3cf5592d2e8f0001c11f1f",
            "backend": "aws-backend-block",
            "size": 500,
            "type": "sc1",
            "region": "ap-south-1",
            "availabilityZone": "ap-south-1a",
            "status": "creating",
            "tags": [
                {
                    "key": "Name",
                    "value": "anvithks"
                }
            ],
            "metadata": {
                "fields": {
                    "CreationTimeAtBackend": {
                        "Kind": {
                            "StringValue": "2020-08-19T09:56:40.293Z"
                        }
                    },
                    "VolumeId": {
                        "Kind": {
                            "StringValue": "vol-0322888eed5227f94"
                        }
                    }
                }
            }
        },
        {
            "id": "5f3cf79f5dc8d300018d8db6",
            "createdAt": "2020-08-19T15:27:51",
            "updatedAt": "2020-08-19T15:27:57",
            "name": "sanil",
            "description": "AWS Volume",
            "tenantId": "94b280022d0c4401bcf3b0ea85870519",
            "userId": "558057c4256545bd8a307c37464003c9",
            "backendId": "5f3cf5592d2e8f0001c11f1f",
            "backend": "aws-backend-block",
            "size": 500,
            "type": "st1",
            "region": "ap-south-1",
            "availabilityZone": "ap-south-1a",
            "status": "available",
            "tags": [
                {
                    "key": "Name",
                    "value": "sanil"
                }
            ],
            "metadata": {
                "fields": {
                    "CreationTimeAtBackend": {
                        "Kind": {
                            "StringValue": "2020-08-19T09:57:51.508Z"
                        }
                    },
                    "VolumeId": {
                        "Kind": {
                            "StringValue": "vol-069aa8d55f90efeee"
                        }
                    }
                }
            }
        },
        {
            "id": "5f3cf7d75dc8d300018d8db7",
            "createdAt": "2020-08-19T15:28:47",
            "updatedAt": "2020-08-19T15:28:53",
            "name": "fannie",
            "description": "AWS Volume",
            "tenantId": "94b280022d0c4401bcf3b0ea85870519",
            "userId": "558057c4256545bd8a307c37464003c9",
            "backendId": "5f3cf5592d2e8f0001c11f1f",
            "backend": "aws-backend-block",
            "size": 1,
            "type": "standard",
            "region": "ap-south-1",
            "availabilityZone": "ap-south-1a",
            "status": "available",
            "tags": [
                {
                    "key": "Name",
                    "value": "fannie"
                }
            ],
            "metadata": {
                "fields": {
                    "CreationTimeAtBackend": {
                        "Kind": {
                            "StringValue": "2020-08-19T09:58:46.998Z"
                        }
                    },
                    "VolumeId": {
                        "Kind": {
                            "StringValue": "vol-0a4a33b0187aac057"
                        }
                    }
                }
            }
        }
    ],
    "next": 5
}
```
8. Get Volume

GET: http://192.168.20.162:8089/v1/94b280022d0c4401bcf3b0ea85870519/volumes/5f3cf65a5dc8d300018d8db3
Response:
```
{
    "id": "5f3cf65a5dc8d300018d8db3",
    "createdAt": "2020-08-19T15:22:26",
    "updatedAt": "2020-08-19T15:22:32",
    "name": "himanshu",
    "description": "AWS Volume",
    "tenantId": "94b280022d0c4401bcf3b0ea85870519",
    "userId": "558057c4256545bd8a307c37464003c9",
    "backendId": "5f3cf5592d2e8f0001c11f1f",
    "backend": "aws-backend-block",
    "size": 1,
    "type": "gp2",
    "region": "ap-south-1",
    "availabilityZone": "ap-south-1a",
    "status": "available",
    "iops": 100,
    "tags": [
        {
            "key": "Name",
            "value": "himanshu"
        }
    ],
    "metadata": {
        "fields": {
            "CreationTimeAtBackend": {
                "Kind": {
                    "StringValue": "2020-08-19T09:52:26.284Z"
                }
            },
            "VolumeId": {
                "Kind": {
                    "StringValue": "vol-03deedaee2de0060f"
                }
            }
        }
    }
}
```

9. PUT Volume

PUT: http://192.168.20.162:8089/v1/94b280022d0c4401bcf3b0ea85870519/volumes/5f3cf65a5dc8d300018d8db3
Request:
```
{
    "description": "AWS Volume Updated",
    "size": 4,
	"type": "io1",
	"iops": 200,
    "tags": [
        {
            "key": "Name",
            "value": "himanshuSODA"
        },
         {
            "key": "Department",
            "value": "Development"
        }
    ]
}
```
Response:
```
{
    "id": "5f3cf65a5dc8d300018d8db3",
    "createdAt": "2020-08-19T15:22:26",
    "updatedAt": "2020-08-19T15:35:02",
    "name": "himanshu",
    "description": "AWS Volume Updated",
    "tenantId": "94b280022d0c4401bcf3b0ea85870519",
    "userId": "558057c4256545bd8a307c37464003c9",
    "backendId": "5f3cf5592d2e8f0001c11f1f",
    "backend": "aws-backend-block",
    "size": 4,
    "type": "io1",
    "region": "ap-south-1",
    "availabilityZone": "ap-south-1a",
    "status": "updating",
    "iops": 200,
    "metadata": {
        "fields": {
            "CreationTimeAtBackend": {
                "Kind": {
                    "StringValue": "2020-08-19T09:52:26.284Z"
                }
            },
            "Progress": {
                "Kind": {
                    "NumberValue": 0
                }
            },
            "StartTimeAtBackend": {
                "Kind": {
                    "StringValue": "2020-08-19T10:05:02Z"
                }
            },
            "VolumeId": {
                "Kind": {
                    "StringValue": "vol-03deedaee2de0060f"
                }
            }
        }
    }
}
```
10. DELETE Volume

DELETE http://192.168.20.162:8089/v1/94b280022d0c4401bcf3b0ea85870519/volumes/5f3cf65a5dc8d300018d8db3
Response: 
{}

**Special notes for your reviewer**:
This PR is for AWS Block Driver.

### CODE REVIEW

**Comment by himanshuvar** [comment]
@wisererik Done

File: api/pkg/block/service.go [hunk 1]
```diff
@@ -1,4 +1,4 @@
-// Copyright 2020 The SODA Authors.
+// Copyright 2020 The OpenSDS Authors.
```
Comment (rajat-soda) [inline api/pkg/block/service.go:1]: Please use SODA instead of OpenSDS .

File: api/pkg/block/service.go [hunk 2]
```diff
@@ -43,6 +47,163 @@ func NewAPIService(c client.Client) *APIService {
...
+func WriteError(response *restful.Response, msg string, errCode int, err error) {
+	log.Errorf(msg, err)
+	error := response.WriteError(errCode, err)
+	if error != nil {
+		log.Errorf("Response write status and http error failed: %v\n", err)
+		return
+	}
+}
+
+func (s *APIService) checkBackendExists(ctx context.Context, request *restful.Request,
```
Comment (rajat-soda) [inline api/pkg/block/service.go:69]: Suggestion  : Can we have a Test Connection kind of a abstraction , that is implemented for each vendor .. as there may be vendor specific way of testing the connectivity

File: api/pkg/block/service.go [hunk 3]
```diff
@@ -74,24 +235,95 @@ func (s *APIService) CreateVolume(request *restful.Request, response *restful.Re
...
 
-	backend := request.QueryParameter(common.REQUEST_PATH_BACKEND_ID)
+	vol := &block.Volume{
+		Description: volume.Description,
+	}
+
+	if volume.Metadata != nil || len(volume.Metadata) != 0 {
+		metadata, err := utils.ConvertMapToStruct(volume.Metadata)
+		if err != nil {
+			log.Errorf("Failed to parse metadata: %v\n", volume.Metadata, err)
```
Comment (rajat-soda) [inline api/pkg/block/service.go:260]: It will be a good idea to move the Error messages to a common file , later it can be use for internationaliation .

File: api/pkg/block/service.go [hunk 4]
```diff
@@ -43,6 +47,163 @@ func NewAPIService(c client.Client) *APIService {
...
+	if backendId != "" {
+		//List volumes for the backend.
+		listVolumeRequest = s.listVolumeByBackend(ctx, request, response, backendId)
+	} else {
+		//List all volumes.
+		listVolumeRequest = s.listVolumeDefault(ctx, request, response)
+	}
+
+	if listVolumeRequest == nil {
+		return
```
Comment (kumarashit) [inline api/pkg/block/service.go:134]: Log before returning

File: api/pkg/block/service.go [hunk 5]
```diff
@@ -43,6 +47,163 @@ func NewAPIService(c client.Client) *APIService {
...
+		Limit:    limit,
+		Offset:   offset,
+		SortKeys: sortKeys,
+		SortDirs: sortDirs,
+		Filter:   filter,
+	}
+}
+
+func (s *APIService) ListVolumes(request *restful.Request, response *restful.Response) {
+	if !policy.Authorize(request, response, "volume:list") {
```
Comment (kumarashit) [inline api/pkg/block/service.go:114]: log before returning

File: api/pkg/block/service.go [hunk 6]
```diff
@@ -43,6 +47,163 @@ func NewAPIService(c client.Client) *APIService {
...
+func (s *APIService) listVolumeDefault(ctx context.Context, request *restful.Request,
+	response *restful.Response) *block.ListVolumeRequest {
+
+	return s.prepareVolumeRequest(request, response)
+}
+
+func (s *APIService) listVolumeByBackend(ctx context.Context, request *restful.Request, response *restful.Response,
+	backendId string) *block.ListVolumeRequest {
+
+	if s.checkBackendExists(ctx, request, response, backendId) != nil {
```
Comment (kumarashit) [inline api/pkg/block/service.go:161]: Should it be BadRequest error?

File: api/pkg/block/service.go [hunk 7]
```diff
@@ -43,6 +47,163 @@ func NewAPIService(c client.Client) *APIService {
...
+	filterQuery, err := common.GetFilter(request, filterQueryOpts)
+	if err != nil {
+		WriteError(response, "Get filter failed: %v\n", http.StatusBadRequest, err)
+		return nil
+	}
+
+	listVolumeRequest := s.prepareVolumeRequest(request, response)
+
+	if listVolumeRequest == nil {
+		return nil
```
Comment (kumarashit) [inline api/pkg/block/service.go:175]: logging

File: api/pkg/block/service.go [hunk 8]
```diff
@@ -74,24 +235,95 @@ func (s *APIService) CreateVolume(request *restful.Request, response *restful.Re
...
 		return
 	}
-	log.Infof("Received request to list volumes")
 
-	backend := request.QueryParameter(common.REQUEST_PATH_BACKEND_ID)
+	vol := &block.Volume{
+		Description: volume.Description,
+	}
+
+	if volume.Metadata != nil || len(volume.Metadata) != 0 {
```
Comment (kumarashit) [inline api/pkg/block/service.go:257]: If volume.metadata is nil then why to check its length?

File: contrib/datastore/block/driver/factory.go [hunk 9]
```diff
@@ -16,25 +16,22 @@ package driver
 
 import (
 	backendpb "github.com/opensds/multi-cloud/backend/proto"
-	excep "github.com/opensds/multi-cloud/block/pkg/exception"
-	log "github.com/sirupsen/logrus"
+	exp "github.com/opensds/multi-cloud/s3/pkg/exception"
```
Comment (kumarashit) [inline contrib/datastore/block/driver/factory.go:19]: Why specific s3? Why cannot we move it to common

**Review by kumarashit — COMMENTED** [review]
One generic comment, logs should have the first letter in lower case.

File: api/pkg/block/service.go (hunk 8 above)
Comment (himanshuvar) [reply api/pkg/block/service.go:257]: metadata can be empty also.
Please check the logic which is to check map for NULLorEmpty
https://www.javaguides.net/2019/04/check-if-map-is-null-or-empty-in-java.html

File: api/pkg/block/service.go (hunk 1 above)
Comment (himanshuvar) [reply api/pkg/block/service.go:1]: Thanks, Done

File: api/pkg/block/service.go (hunk 2 above)
Comment (himanshuvar) [reply api/pkg/block/service.go:69]: Just to clarify this a check for Cloud Backend resource existence in Backend Service. No Vendor Connectivity Checks here. :)

**Comment by himanshuvar** [comment]
> 
> 
> One generic comment, logs should have the first letter in lower case.

I have followed the existing multi-cloud project services logging schemes/format. If We need to update, We need to define generalized logging format rules & refactor the code.

File: api/pkg/block/service.go (hunk 4 above)
Comment (himanshuvar) [reply api/pkg/block/service.go:134]: Done, Thanks

File: api/pkg/block/service.go (hunk 5 above)
Comment (himanshuvar) [reply api/pkg/block/service.go:114]: Logging has been taken care in the calling function.

File: api/pkg/block/service.go (hunk 6 above)
Comment (himanshuvar) [reply api/pkg/block/service.go:161]: Here it is to check for backend resource object existence. It should be a 404 Error if no Backend resource exist

File: api/pkg/block/service.go (hunk 7 above)
Comment (himanshuvar) [reply api/pkg/block/service.go:175]: Done, Thanks

File: contrib/datastore/block/driver/factory.go (hunk 9 above)
Comment (himanshuvar) [reply contrib/datastore/block/driver/factory.go:19]: Yes, We need to refactor the duplicate code for maintaing Exceptions across services. As if now I have updated to your's block code Exception.

File: api/pkg/block/service.go (hunk 3 above)
Comment (himanshuvar) [reply api/pkg/block/service.go:260]: Yes, There is lot scope for making generalization for logging, exceptions, Error handling for multi-cloud.
Thanks for your valuable suggestion.

File: api/pkg/block/service.go (hunk 8 above)
Comment (kumarashit) [reply api/pkg/block/service.go:259]: Thanks for the link.
But in case of golang, even checking len(volume.Metadata) != 0 should be fine, as len of nil is 0

**Comment by kumarashit** [comment]
> > One generic comment, logs should have the first letter in lower case.
> 
> I have followed the existing multi-cloud project services logging schemes/format. If We need to update, We need to define generalized logging format rules & refactor the code.

As a generic rule and golang suggestions, better to log the error messages starting with lowecase

**Review by kumarashit — APPROVED** [review]
LGTM

**Comment by rajat-soda** [comment]
LGTM

**Comment by kumarashit** [comment]
Please update the PR abstract and provide details.

**Comment by skdwriting** [comment]
@wisererik himanshu has replied to your comments. Please check and close.

**Comment by skdwriting** [comment]
> @wisererik himanshu has replied to your comments. Please check and close.

Please see the PR description

**Comment by kumarashit** [comment]
@wisererik @sfzeng please check this PR

**Review by wisererik — APPROVED** [review]
LGTM
