### PR TITLE
Fix issue-1225

### LINKED ISSUE #1225: Getting 500 error while accessing s3 service in HA
**Issue/Feature Description:**

Getting the error
err={"id":"go.micro.client","code":500,"detail":"service xxxx: not found","status":"Internal Server Error"}
while accessing S3 service. 

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Bucket creation will not happen if this is not fixed. 

**How to reproduce, in case of a bug:**

Install HA and try to create bucket. 

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by rajat-soda**
**What type of PR is this?**
Issue Fix PR.

> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind new feature
kind bug fix
> /kind cleanup
> /kind revert change
> /kind design
> /kind documentation
> /kind enhancement

**What this PR does / why we need it**:
Accessing S3 Service give error.. 
err={"id":"go.micro.client","code":500,"detail":"service s3: not found","status":"Internal Server Error"}

**Which issue(s) this PR fixes**:

Fixes #1225 

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
image

**Test Report**:

image

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rajat-soda** [comment]
@kumarashit , Please review and merge..

File: K8s/k8s-deploy.sh [hunk 1]
```diff
@@ -32,6 +32,13 @@ kubectl apply -f redis-service.yaml
 kubectl apply -f kafka-service.yaml
 kubectl apply -f api-service.yaml
 kubectl apply -f s3api-service.yaml
+kubectl apply -f s3-service.yaml
```
Comment (asifdxtreme) [inline K8s/k8s-deploy.sh:35]: Instead of adding so much of appy statement, you can put all the yaml in a directory and just put 1 statement as `kubectl apply -f directoryName/`

File: api/pkg/s3/service.go [hunk 2]
```diff
@@ -30,8 +31,13 @@ import (
 )
 
 const (
-	s3Service      = "s3"
-	backendService = "backend"
+        MICRO_ENVIRONMENT = "MICRO_ENVIRONMENT"
```
Comment (asifdxtreme) [inline api/pkg/s3/service.go:34]: please run `go fmt` on the changes to allign the code

File: K8s/k8s-deploy.sh (hunk 1 above)
Comment (rajat-soda) [reply K8s/k8s-deploy.sh:35]: Yes there is an issue opened for this.. As it has no impact.. will be taken up as a backlog.

File: K8s/kafka-deployment.yaml [hunk 3]
```diff
@@ -18,31 +18,31 @@ kind: Deployment
 metadata:
   namespace: soda-multi-cloud
   labels:
-    io.soda.service: kafka-svc
-  name: kafka-svc
+    io.soda.service: kafka
+  name: kafka
```
Comment (AmitRoushan) [inline K8s/kafka-deployment.yaml:22]: IMO, if deployment labels are changes, service labels need to get changed aswell

**Review by AmitRoushan — CHANGES_REQUESTED** [review]

**Comment by AmitRoushan** [comment]
Wanted to understand why mongodb deployment cleanup are removed as part of this fix

File: go.mod [hunk 4]
```diff
@@ -29,10 +29,13 @@ require (
 	github.com/huaweicloud/huaweicloud-sdk-go-v3 v0.0.16-beta
 	github.com/journeymidnight/radoshttpd v0.0.0-20190617133011-609666b51136
 	github.com/journeymidnight/yig v2.0.0+incompatible
+	github.com/mholt/certmagic v0.9.3 // indirect
 	github.com/micro/go-log v0.1.0
-	github.com/micro/go-micro/v2 v2.6.0
+	github.com/micro/go-micro/v2 v2.9.1
+	github.com/micro/go-plugins/registry/kubernetes/v2 v2.9.1
```
[the remark this answers is not in the document]
Comment (rajat-soda) [reply go.mod:35]: no its , a direct dependency. Its the latest version of go-micro, 
Kubernetes plugin is  used to support kubernetes as registry for go-micro

File: K8s/kafka-deployment.yaml (hunk 3 above)
Comment (rajat-soda) [reply K8s/kafka-deployment.yaml:22]: service is already having the right name !

File: go.sum [hunk 5]
```diff
@@ -1,961 +0,0 @@
-cloud.google.com/go v0.26.0/go.mod h1:aQUYkXzVsufM+DwF1aE+0xfcU+56JwCaLick0ClmMTw=
```
[the remark this answers is not in the document]
Comment (rajat-soda) [reply go.sum]: Added.

**Comment by rajat-soda** [comment]
> Wanted to understand why mongodb deployment cleanup are removed as part of this fix

Its refactored into another k8s-clean-mongo.sh .  The cleanup script is a utility script for manual cleanup. No impact.

File: K8s/k8s-deploy.sh (hunk 1 above)
Comment (sushanthakumar) [reply K8s/k8s-deploy.sh:35]: Same opinion here

**Comment by sushanthakumar** [comment]
No new comment from my side, LGTM

**Review by AmitRoushan — APPROVED** [review]
LGTM

**Review by kumarashit — APPROVED** [review]
LGTM

**Review by asifdxtreme — APPROVED** [review]
LGTM

**Review by NajmudheenCT — APPROVED** [review]
LGTM
