### PR TITLE
Validation of invalid region,ak,sk values while creating backend

### LINKED ISSUE #1108: [Backend Service] Backend Registration is Successful Even for Invalid Region
**Issue/Feature Description:** Backend Registration is Successful even for a Invalid Region
This should be 400 Error message for this operation

**Why this issue to fixed / feature is needed(give scenarios or use cases):** To provide Negative Scenarios for Backend Creation

**How to reproduce, in case of a bug:**

Create backend for the following:
POST http://192.168.20.162:8089/v1/94b280022d0c4401bcf3b0ea85870519/backends

```
{
  "name": "gcp-backend-file",
  "type": "gcp-file",
  "Region": "fake region",
  "Access": "access_key",
  "Security": "secret_key"
}
```

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by vineela1999**
**What type of PR is this?**
  kind enhancement

**What this PR does / why we need it**:
this  checks the validation of credentials  when creating backend
**Which issue(s) this PR fixes**:

Fixes 
#1108 
#1109 
#1110 

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
> /kind NOT-TESTED

**Test Report**:
valid credentials:
WhatsApp Image 2020-12-29 at 11 49 10 PM

valid credentials:
Screenshot from 2020-12-29 23-07-41

fake region:
WhatsApp Image 2020-12-29 at 11 48 33 PM

Fake region:
Screenshot from 2020-12-29 23-03-19

fake access key:
WhatsApp Image 2020-12-29 at 11 46 41 PM

Fake access key:
Screenshot from 2020-12-29 23-04-03

fake secret key:
WhatsApp Image 2020-12-29 at 11 50 26 PM

Fake secret key:
image

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rhsakarpos** [comment]
@vineela1999 can you please resolve the conflicted files and update again for review ? thanks.

File: s3/pkg/datastore/azure/azure.go [hunk 1]
```diff
@@ -331,6 +332,76 @@ func (ad *AzureAdapter) ListParts(ctx context.Context, multipartUpload *pb.ListP
 	return nil, ErrNotImplemented
 }
 
+func (ad *AzureAdapter) BackendCheck(ctx context.Context, backendDetail *pb.BackendDetailS3) error {
```
Comment (rhsakarpos) [inline s3/pkg/datastore/azure/azure.go:335]: @vineela1999 can we replace this code by re-using code ?
question is

- can backendCheck be an aggregate API ?
- it can call existing methods putObject, deleteObject to do the check

File: s3/pkg/datastore/azure/azure.go [hunk 2]
```diff
@@ -331,6 +332,76 @@ func (ad *AzureAdapter) ListParts(ctx context.Context, multipartUpload *pb.ListP
...
+
+	object := pb.Object{
+		BucketName: backendDetail.BucketName,
+		ObjectKey:  "emptyContainer/",
+	}
+	objectId := object.BucketName + "/" + object.ObjectKey
+	blobURL := containerURL.NewBlockBlobURL(objectId)
+	bs := []byte{0}
+	stream := bytes.NewReader(bs)
+	options := azblob.UploadStreamToBlockBlobOptions{BufferSize: 2 * 1024 * 1024, MaxBuffers: 2}
```
Comment (rhsakarpos) [inline s3/pkg/datastore/azure/azure.go:383]: @vineela1999 please add constants here, remove the magic numbers

File: s3/pkg/datastore/ceph/ceph.go [hunk 3]
```diff
@@ -310,6 +310,10 @@ func (ad *CephAdapter) ListParts(ctx context.Context, multipartUpload *pb.ListPa
 	return nil, ErrNotImplemented
 }
 
+func (ad *CephAdapter) BackendCheck(ctx context.Context, backendDetail *pb.BackendDetailS3) error {
+	return nil
```
Comment (rhsakarpos) [inline s3/pkg/datastore/ceph/ceph.go:314]: @vineela1999 nil means success, right ?
do you want to distinguish between nil(successful check) and not-implemented instead ?

File: s3/pkg/service/service.go [hunk 4]
```diff
@@ -522,6 +523,22 @@ func (s *s3Service) CountObjects(ctx context.Context, in *pb.ListObjectsRequest,
 	return nil
 }
 
+func (s *s3Service) BackendCheck(ctx context.Context, backendDetail *pb.BackendDetailS3, Null *pb.Null) error {
+	log.Info("backendCheck is called in s3 service.")
+	backendDetailtry := &backend.BackendDetail{}
```
Comment (rhsakarpos) [inline s3/pkg/service/service.go:528]: @vineela1999 why are we making a copy here ?

File: s3/proto/s3.proto [hunk 5]
```diff
@@ -706,3 +709,18 @@ message ListBucketUploadResponse {
...
 }
+
+message BackendDetailS3 {
+	string id = 1;
+	string tenantId = 2;
+	string userId = 3;
+	string name = 4;
+	string type = 5;
+	string region = 6;
+	string endpoint = 7;
```
Comment (rhsakarpos) [inline s3/proto/s3.proto:720]: @vineela1999 camelCase please

File: api/pkg/backend/service.go [hunk 6]
```diff
@@ -205,17 +204,60 @@ func (s *APIService) CreateBackend(request *restful.Request, response *restful.R
...
+	backendDetailtry.Name = backendDetail.Name
+	backendDetailtry.Type = backendDetail.Type
+	backendDetailtry.Region = backendDetail.Region
+	backendDetailtry.Endpoint = backendDetail.Endpoint
+	backendDetailtry.BucketName = backendDetail.BucketName
+	backendDetailtry.Access = backendDetail.Access
+	backendDetailtry.Security = backendDetail.Security
+
+	_, err = s.s3Client.BackendCheck(ctx, backendDetailtry)
+	err1 := errors.New("failed to create backend due to invalid credentials")
```
Comment (rhsakarpos) [inline api/pkg/backend/service.go:232]: @vineela1999 how do we know it is due to invalid credentials ? or some other reason ?

File: api/pkg/backend/service.go [hunk 7]
```diff
@@ -205,17 +204,60 @@ func (s *APIService) CreateBackend(request *restful.Request, response *restful.R
...
+
+	if err != nil {
+		log.Errorf("failed to create backend due to wrong credentials: %v\n", err)
+		response.WriteError(http.StatusBadRequest, err1)
+		return
+	}
+
 	res, err := s.backendClient.CreateBackend(ctx, &backend.CreateBackendRequest{Backend: backendDetail})
```
Comment (rhsakarpos) [inline api/pkg/backend/service.go:240]: @vineela1999 confused here, why do we createBackend 2 times ? please explain the pseudo code here. Can we do this
`createBackend`
`checkBackend`
`if(pass) `
      `retainBackend `
`else `
    `deleteBackend`

File: api/pkg/backend/service.go [hunk 8]
```diff
@@ -205,17 +204,60 @@ func (s *APIService) CreateBackend(request *restful.Request, response *restful.R
...
 		response.WriteError(http.StatusInternalServerError, err)
 		return
 	}
 
-	log.Info("Create backend successfully.")
+	log.Info("Created backend successfully.")
 	response.WriteEntity(res.Backend)
 }
 
+func typeExists(slice []*backend.TypeDetail, inputType string) bool {
```
Comment (rhsakarpos) [inline api/pkg/backend/service.go:251]: @vineela1999 suggest to rename variable slice (type vs. what the variable holds)

File: api/pkg/backend/service.go [hunk 9]
```diff
@@ -205,17 +204,60 @@ func (s *APIService) CreateBackend(request *restful.Request, response *restful.R
...
+	for _, item := range slice {
+		if item.Name == inputType {
+			log.Debug("backend type is valid")
```
Comment (rhsakarpos) [inline api/pkg/backend/service.go:254]: @vineela1999 insufficient logs...which backend type is valid ? value ?

File: api/pkg/backend/service.go [hunk 10]
```diff
@@ -205,17 +204,60 @@ func (s *APIService) CreateBackend(request *restful.Request, response *restful.R
...
 	}
 
-	log.Info("Create backend successfully.")
+	log.Info("Created backend successfully.")
 	response.WriteEntity(res.Backend)
 }
 
+func typeExists(slice []*backend.TypeDetail, inputType string) bool {
+	for _, item := range slice {
+		if item.Name == inputType {
```
Comment (rhsakarpos) [inline api/pkg/backend/service.go:253]: @vineela1999 can item.Name be null ?

File: api/pkg/backend/service.go (hunk 8 above)
Comment (rhsakarpos) [inline api/pkg/backend/service.go:251]: @vineela1999 please add comments for all methods and code
in this case, is this a type sensitive compare ?

**Comment by anvithks** [comment]
@vineela1999 avoid force pushing commits as it overwrites any reviews and discusssions.

File: s3/pkg/datastore/azure/azure.go (hunk 1 above)
Comment (vineela1999) [reply s3/pkg/datastore/azure/azure.go:334]: Yes done thanks

File: s3/pkg/service/service.go (hunk 4 above)
Comment (vineela1999) [reply s3/pkg/service/service.go:546]: because it doesnt accept BackendDetail of backend  its require to copy values of it to BackendDetailS3 of S3

File: api/pkg/backend/service.go (hunk 6 above)
Comment (vineela1999) [reply api/pkg/backend/service.go]: because here we are getting error from BackendCheck function it is due to invalid credentials only

**Review by anvithks — CHANGES_REQUESTED** [review]
Tested the dashboard using the branch. 

**Invalid AK**
The messages should read 
`Failed to register backend due to invalid credentials.`
We are not creating a backend here but registering an existing one. 
image


**Invalid SK**
The messages should read 
`Failed to register backend due to invalid credentials.`
We are not creating a backend here but registering an existing one. 
image

**Invalid Region**
The error is due to invalid region. the error should say invalid region.
image

File: s3/pkg/service/service.go [hunk 11]
```diff
@@ -541,6 +541,32 @@ func (s *s3Service) CountObjects(ctx context.Context, in *pb.ListObjectsRequest,
 	return nil
 }
 
+func (s *s3Service) BackendCheck(ctx context.Context, backendDetail *pb.BackendDetailS3, out *pb.BaseResponse) error {
+	log.Info("backendCheck is called in s3 service.")
```
Comment (kumarashit) [inline s3/pkg/service/service.go:545]: Make the Info messages started with Upper case

File: s3/pkg/service/service.go [hunk 12]
```diff
@@ -541,6 +541,32 @@ func (s *s3Service) CountObjects(ctx context.Context, in *pb.ListObjectsRequest,
...
+	backendDetailtry.Access = backendDetail.Access
+	backendDetailtry.Security = backendDetail.Security
+	sd, err := driver.CreateStorageDriver(backendDetail.Type, backendDetailtry)
+	if err != nil {
+		log.Errorf("adapter creation failed, err:%v\n", err)
+		return err
+	}
+
+	err = sd.BackendCheck(ctx, backendDetail)
+	if err != nil {
```
Comment (kumarashit) [inline s3/pkg/service/service.go:562]: run go fmt..seems formatting issues

**Review by kumarashit — APPROVED** [review]

File: api/pkg/backend/service.go [hunk 13]
```diff
@@ -217,6 +217,25 @@ func (s *APIService) CreateBackend(request *restful.Request, response *restful.R
 		response.WriteError(http.StatusBadRequest, err)
 		return
 	}
+
+	backendDetailtry := &s3.BackendDetailS3{}
```
[the remark this answers is not in the document]
Comment (kumarashit) [reply api/pkg/backend/service.go:221]: Please check

File: s3/pkg/datastore/azure/azure.go (hunk 2 above)
Comment (vineela1999) [reply s3/pkg/datastore/azure/azure.go]: code is removed

File: s3/pkg/datastore/ceph/ceph.go (hunk 3 above)
Comment (vineela1999) [reply s3/pkg/datastore/ceph/ceph.go]: yes changed

File: s3/proto/s3.proto (hunk 5 above)
Comment (vineela1999) [reply s3/proto/s3.proto]: yes will change

File: api/pkg/backend/service.go (hunk 7 above)
Comment (vineela1999) [reply api/pkg/backend/service.go:239]: only once createBackend is used

File: api/pkg/backend/service.go (hunk 8 above)
Comment (vineela1999) [reply api/pkg/backend/service.go]: code is already merged

File: api/pkg/backend/service.go (hunk 9 above)
Comment (vineela1999) [reply api/pkg/backend/service.go]: code is already merged

File: api/pkg/backend/service.go (hunk 8 above)
Comment (vineela1999) [reply api/pkg/backend/service.go]: code is merged

File: api/pkg/backend/service.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (vineela1999) [reply api/pkg/backend/service.go:221]: yes changed variable

File: api/pkg/backend/service.go [hunk 14]
```diff
@@ -217,6 +217,25 @@ func (s *APIService) CreateBackend(request *restful.Request, response *restful.R
...
+	backendDetailtry.Name = backendDetail.Name
+	backendDetailtry.Type = backendDetail.Type
+	backendDetailtry.Region = backendDetail.Region
+	backendDetailtry.Endpoint = backendDetail.Endpoint
+	backendDetailtry.BucketName = backendDetail.BucketName
+	backendDetailtry.Access = backendDetail.Access
+	backendDetailtry.Security = backendDetail.Security
+
+	_, err = s.s3Client.BackendCheck(ctx, backendDetailtry)
+	err1 := errors.New("failed to create backend due to invalid credentials\n")
```
[the remark this answers is not in the document]
Comment (vineela1999) [reply api/pkg/backend/service.go]: removed

File: api/pkg/backend/service.go [hunk 15]
```diff
@@ -217,6 +217,25 @@ func (s *APIService) CreateBackend(request *restful.Request, response *restful.R
...
+	if err != nil {
+		log.Errorf("failed to create backend due to wrong credentials: %v\n", err)
```
[the remark this answers is not in the document]
Comment (vineela1999) [reply api/pkg/backend/service.go]: done

File: s3/pkg/datastore/aws/aws.go [hunk 16]
```diff
@@ -381,6 +381,27 @@ func (ad *AwsAdapter) ListParts(ctx context.Context, multipartUpload *pb.ListPar
 	return nil, errors.New("not implemented yet.")
 }
 
+func (ad *AwsAdapter) BackendCheck(ctx context.Context, backendDetail *pb.BackendDetailS3) error {
+	log.Debug("Error in creating the session %v", ctx)
```
[the remark this answers is not in the document]
Comment (vineela1999) [reply s3/pkg/datastore/aws/aws.go]: removed

File: s3/pkg/service/service.go (hunk 11 above)
Comment (vineela1999) [reply s3/pkg/service/service.go]: done

File: s3/pkg/service/service.go (hunk 12 above)
Comment (vineela1999) [reply s3/pkg/service/service.go:562]: format is done

**Review by kumarashit — APPROVED** [review]
LGTM

**Review by skdwriting — APPROVED** [review]
LGTM
