### PR TITLE
Fixing archival issue for AWS and Azure

### LINKED ISSUE #1227: Cloud Data Archival is broken for Azure and AWS
**Issue/Feature Description:**
The Data Archival and retrieval is broken for AWS and Azure

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Due to changes for bucket Management policy and dev to master sync, this feature is broken

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by kumarashit**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind new feature
/kind bug fix
> /kind cleanup
> /kind revert change
> /kind design
> /kind documentation
> /kind enhancement

**What this PR does / why we need it**:
Fixing the issue of archival and restore for AWS and Azure. Changed the way objectID was being passed. 

**Which issue(s) this PR fixes**:
Fixes #1227 

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
 /kind TESTED
> /kind NOT-TESTED
**AZURE**
image
image
image
image
**AWS**
image
image
image
image
**GCP**
image
image

**Special notes for your reviewer**:
Dev branch (hos_dev) includes the bucket management changes. This need to be incorporated for the master. Also, the dev to master sync had some code removed for master. Fixes those

### CODE REVIEW

File: s3/pkg/datastore/azure/azure.go [hunk 1]
```diff
@@ -148,14 +151,20 @@ func (ad *AzureAdapter) Put(ctx context.Context, stream io.Reader, object *pb.Ob
...
-	storClass, err := osdss3.GetNameFromTier(object.Tier, utils.OSTYPE_Azure)
-	if err != nil {
-		log.Infof("Translate tier[%d] to aws storage class failed\n", object.Tier)
-		return result, ErrInternalError
+	var storClass string
+
+	if storageClass != "" {
+		storClass = storageClass
+	} else {
+		if object.Tier == 0 {
```
Comment (AmitRoushan) [inline s3/pkg/datastore/azure/azure.go:159]: Nit: can maintain one "non Tier" constant

File: s3/pkg/datastore/azure/azure.go [hunk 2]
```diff
@@ -67,7 +69,7 @@ func (ad *AzureAdapter) BucketCreate(ctx context.Context, input *pb.Bucket) erro
 	// Create the container on the service (with no metadata and no public access)
 	_, err := containerURL.Create(ctx, azblob.Metadata{}, azblob.PublicAccessNone)
 	if err != nil {
-		log.Error("failed to create bucket:",err)
+		log.Error("failed to create bucket:", err)
```
Comment (rajat-soda) [inline s3/pkg/datastore/azure/azure.go:72]: One generic comment across services  : Most of the places we log the error/warning and Users don't have  a way of knowing what went wrong. UI is not getting / capturing any error scenarios well.. This could be a task for Next Rel. 
This should be handled in a generic way for all Multi-Cloud Services.

**Comment by rajat-soda** [comment]
LGTM

File: s3/pkg/datastore/azure/azure.go (hunk 2 above)
Comment (kumarashit) [reply s3/pkg/datastore/azure/azure.go:72]: Yes. This is one of the long pending enhancement. I will open issue to track.

Comment (kumarashit) [reply s3/pkg/datastore/azure/azure.go:72]: https://github.com/sodafoundation/multi-cloud/issues/1229

File: s3/pkg/datastore/azure/azure.go (hunk 1 above)
Comment (kumarashit) [reply s3/pkg/datastore/azure/azure.go]: Changed. Please check

**Review by AmitRoushan — APPROVED** [review]
LGTM

**Comment by PravinRanjan10** [comment]
LGTM

**Review by NajmudheenCT — APPROVED** [review]
LGTM

**Review by skdwriting — APPROVED** [review]
LGTM
