### PR TITLE
Get FileShare API Support

### LINKED ISSUE #1019: Get FileShare API support
**Issue/Feature Description:**
GET API support for FileShare to get the details of a particular fileshare
`[GET] /v1/<tenantId>/file/shares/<id>`

**Why this issue to fixed / feature is needed(give scenarios or use cases):** To support GET FileShare API

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by himanshuvar**
**What type of PR is this?**

> /kind new feature

**What this PR does / why we need it**:
GET API support for FileShare to get the details of a particular fileshare
`[GET] /v1/<tenantId>/file/shares/<id>`

**Which issue(s) this PR fixes**:

Fixes #1019 

**Test Report Added?**:

> /kind TESTED

**Test Report**:

The following testing is done for List File Share API:

- [x] List Backend

- [x] Get FileShare

- [x] List File Share for Azure Backend

- [x] List File Share for AWS Backend

- [x] List all File Share

```
List Backends:

http://192.168.20.162:8089/v1/94b280022d0c4401bcf3b0ea85870519/backends

{
    "backends": [
        {
            "id": "5eecefa90de5c3000151d1d4",
            "tenantId": "94b280022d0c4401bcf3b0ea85870519",
            "userId": "558057c4256545bd8a307c37464003c9",
            "name": "azure-backend-file",
            "type": "azure-file",
            "region": "East Asia",
            "endpoint": "https://myaccount.file.core.windows.net/",
            "bucketName": "container"
        },
        {
            "id": "5eecefe30de5c3000151d1d5",
            "tenantId": "94b280022d0c4401bcf3b0ea85870519",
            "userId": "558057c4256545bd8a307c37464003c9",
            "name": "aws-backend-file",
            "type": "aws-file",
            "region": "ap-south-1",
            "endpoint": "s3.amazonaws.com",
            "bucketName": "opensds-him"
        }
    ],
    "next": 2
}

Get File Share

http://192.168.20.162:8089/v1/94b280022d0c4401bcf3b0ea85870519/file/shares/5eecf099a4fb8b25102593a4

{
            "id": "5eecf099a4fb8b25102593a4",
            "createdAt": "2020-06-11T01:12:32.662883Z",
            "updatedAt": "2020-06-11T01:12:34.682329Z",
            "name": "azure-fileshareDemo",
            "description": "Azure FileShare",
            "tenantId": "94b280022d0c4401bcf3b0ea85870519",
            "userId": "558057c4256545bd8a307c37464003c9",
            "backendId": "5eecefa90de5c3000151d1d4",
            "backend": "azure-backend-file",
            "type": "generalPurpose",
            "region": "Southeast Asia",
            "availabilityZone": "Southeast Asia",
            "status": "success"
  }

List File Share for Azure Backend:

http://192.168.20.162:8089/v1/94b280022d0c4401bcf3b0ea85870519/file/shares?backendId=5eecefa90de5c3000151d1d4

{
    "fileshares": [
        {
            "id": "5eecf099a4fb8b25102593a4",
            "createdAt": "2020-06-11T01:12:32.662883Z",
            "updatedAt": "2020-06-11T01:12:34.682329Z",
            "name": "azure-fileshareDemo",
            "description": "Azure FileShare",
            "tenantId": "94b280022d0c4401bcf3b0ea85870519",
            "userId": "558057c4256545bd8a307c37464003c9",
            "backendId": "5eecefa90de5c3000151d1d4",
            "backend": "azure-backend-file",
            "type": "generalPurpose",
            "region": "Southeast Asia",
            "availabilityZone": "Southeast Asia",
            "status": "success"
        }
    ],
    "next": 1
}

List File Share for AWS Backend:

http://192.168.20.162:8089/v1/94b280022d0c4401bcf3b0ea85870519/file/shares?backendId=5eecefe30de5c3000151d1d5

{
    "fileshares": [
        {
            "id": "5eecf38aa4fb8b25102593a5",
            "createdAt": "2020-06-11T01:12:29.662883Z",
            "updatedAt": "2020-06-11T01:12:31.682329Z",
            "name": "aws-fileshareDemo",
            "description": "AWS FileShare",
            "tenantId": "94b280022d0c4401bcf3b0ea85870519",
            "userId": "558057c4256545bd8a307c37464003c9",
            "backendId": "5eecefe30de5c3000151d1d5",
            "backend": "aws-backend-file",
            "type": "bursting",
            "region": "ap-south-1",
            "availabilityZone": "ap-south-1a",
            "status": "success",
            "tags": [
                {
                    "key": "Name",
                    "value": "FSName"
                },
                {
                    "key": "Department",
                    "value": "Billing"
                }
            ]
        },
        {
            "id": "5eecf3c0a4fb8b25102593a6",
            "createdAt": "2020-06-11T01:12:29.662883Z",
            "updatedAt": "2020-06-11T01:12:31.682329Z",
            "name": "aws-fileshare-test",
            "description": "AWS FileShare",
            "tenantId": "94b280022d0c4401bcf3b0ea85870519",
            "userId": "558057c4256545bd8a307c37464003c9",
            "backendId": "5eecefe30de5c3000151d1d5",
            "backend": "aws-backend-file",
            "type": "generalPurpose",
            "region": "ap-south-1",
            "availabilityZone": "ap-south-1b",
            "status": "success",
            "tags": [
                {
                    "key": "Name",
                    "value": "TestFS"
                },
                {
                    "key": "Department",
                    "value": "Testing"
                }
            ]
        }
    ],
    "next": 2
}

List all File Share:

http://192.168.20.162:8089/v1/94b280022d0c4401bcf3b0ea85870519/file/shares

{
    "fileshares": [
        {
            "id": "5eecf099a4fb8b25102593a4",
            "createdAt": "2020-06-11T01:12:32.662883Z",
            "updatedAt": "2020-06-11T01:12:34.682329Z",
            "name": "azure-fileshareDemo",
            "description": "Azure FileShare",
            "tenantId": "94b280022d0c4401bcf3b0ea85870519",
            "userId": "558057c4256545bd8a307c37464003c9",
            "backendId": "5eecefa90de5c3000151d1d4",
            "backend": "azure-backend-file",
            "type": "generalPurpose",
            "region": "Southeast Asia",
            "availabilityZone": "Southeast Asia",
            "status": "success"
        },
        {
            "id": "5eecf38aa4fb8b25102593a5",
            "createdAt": "2020-06-11T01:12:29.662883Z",
            "updatedAt": "2020-06-11T01:12:31.682329Z",
            "name": "aws-fileshareDemo",
            "description": "AWS FileShare",
            "tenantId": "94b280022d0c4401bcf3b0ea85870519",
            "userId": "558057c4256545bd8a307c37464003c9",
            "backendId": "5eecefe30de5c3000151d1d5",
            "backend": "aws-backend-file",
            "type": "bursting",
            "region": "ap-south-1",
            "availabilityZone": "ap-south-1a",
            "status": "success",
            "tags": [
                {
                    "key": "Name",
                    "value": "FSName"
                },
                {
                    "key": "Department",
                    "value": "Billing"
                }
            ]
        },
        {
            "id": "5eecf3c0a4fb8b25102593a6",
            "createdAt": "2020-06-11T01:12:29.662883Z",
            "updatedAt": "2020-06-11T01:12:31.682329Z",
            "name": "aws-fileshare-test",
            "description": "AWS FileShare",
            "tenantId": "94b280022d0c4401bcf3b0ea85870519",
            "userId": "558057c4256545bd8a307c37464003c9",
            "backendId": "5eecefe30de5c3000151d1d5",
            "backend": "aws-backend-file",
            "type": "generalPurpose",
            "region": "ap-south-1",
            "availabilityZone": "ap-south-1b",
            "status": "success",
            "tags": [
                {
                    "key": "Name",
                    "value": "TestFS"
                },
                {
                    "key": "Department",
                    "value": "Testing"
                }
            ]
        }
    ],
    "next": 3
}



<!--
*Please provide the test report link (public accessible, screen shot or copy paste the test report, 
or add the testing details.
-->

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sfzeng** [comment]
For the GetFileShare part, LGTM.

File: file/pkg/service/service.go [hunk 1]
```diff
@@ -80,3 +82,44 @@ func (f *fileService) ListFileShare(ctx context.Context, in *pb.ListFileShareReq
...
+		Id:                 fs.Id.Hex(),
+		CreatedAt:          fs.CreatedAt,
+		UpdatedAt:          fs.UpdatedAt,
+		Name:               fs.Name,
+		Description:        fs.Description,
+		TenantId:           fs.TenantId,
+		UserId:             fs.UserId,
+		BackendId:          fs.BackendId,
+		Backend:            fs.Backend,
+		Size:               fs.Size / utils.GB_FACTOR,
```
Comment (kumarashit) [inline file/pkg/service/service.go:111]: Why the conversion here? Let's report in bytes and leave it to client to convert

File: file/pkg/service/service.go [hunk 2]
```diff
@@ -80,3 +82,44 @@ func (f *fileService) ListFileShare(ctx context.Context, in *pb.ListFileShareReq
...
+	}
+	var tags []*pb.Tag
+	for _, tag := range fs.Tags {
+		tags = append(tags, &pb.Tag{
+			Key:   tag.Key,
+			Value: tag.Value,
+		})
+	}
+	out.Fileshare = &pb.FileShare{
+		Id:                 fs.Id.Hex(),
```
Comment (kumarashit) [inline file/pkg/service/service.go:102]: Is this ID auto-generated? What about the actual ID of the FS from cloud..Like AWS has their own FS-ID reported, which is used for further File ops...For Azure there is no ID returned but the ops can be done on Name

File: file/pkg/service/service.go (hunk 1 above)
Comment (himanshuvar) [reply file/pkg/service/service.go:111]: Yes, The API takes Size in GiB and We are persisting in our DB in bytes.
So the conversion is required.

In case of Azure, The API send size in GiB. So keeping the request response consistent. Conversion is required for reporting it back as requested in the request body.

File: file/pkg/service/service.go (hunk 2 above)
Comment (himanshuvar) [reply file/pkg/service/service.go:102]: Yes, This ID is auto generated to persist in mongo DB.
The backend specific ID are persisted as part of metadata.

File: file/pkg/service/service.go (hunk 1 above)
Comment (kumarashit) [reply file/pkg/service/service.go:111]: Got it..But better we report it in Bytes and let the API consumer convert it into MB, GB,TB or etc.. It will make consistent. thanks

**Comment by kumarashit** [comment]
> For the GetFileShare part, LGTM.

Thanks @sfzeng . There is an issue created by you for the other issue and will track it

File: file/pkg/service/service.go (hunk 1 above)
Comment (himanshuvar) [reply file/pkg/service/service.go]: Code changes Done.
Thanks
