### PR TITLE
[GCP FileShare Support]  Implement Create Fileshare API for GCP Fileshare Driver

### LINKED ISSUE #1076: [GCP FileShare Support] Implement GCP FileShare Create API
**Issue/Feature Description:** Provide Implementation for GCP FileShare Creation

**Why this issue to fixed / feature is needed(give scenarios or use cases):** To support GCP FileShare creation operation

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by himanshuvar**
**What type of PR is this?**
> /kind new feature

**What this PR does / why we need it**: This PR is needed to support File Share Creation for GCP cloud backend.

**Which issue(s) this PR fixes**:

Fixes #1076 

**Test Report Added?**:
> /kind TESTED

**Test Report**:

The following testing is done for Create File Share API for GCP cloud backend:

- [x] Register Backend

- [x] List Backend

- [x] Create FileShare for GCP Backend

**Register a Backend**

Example 1: Registering an Azure Backend for File Share

POST http://192.168.20.162:8089/v1/94b280022d0c4401bcf3b0ea85870519/backends

Request:
```
{
  "name": "gcp-backend-file",
  "type": "gcp-file",
  "Region": "<project_id>",
  "Access": "<access_key>",
  "Security": "<secret_key>"
}
```
Response:
```
{
    "id": "5f66397740852a0001bcc3f7",
    "tenantId": "94b280022d0c4401bcf3b0ea85870519",
    "userId": "558057c4256545bd8a307c37464003c9",
    "name": "gcp-backend-file",
    "type": "gcp-file",
    "region": "<project_id>",
    "access": "<access_key>",
    "security": "<secret_key>"
}
```
**List Backend:**
GET http://192.168.20.162:8089/v1/94b280022d0c4401bcf3b0ea85870519/backends
Response:
```
{
    "backends": [
        {
            "id": "5f66397740852a0001bcc3f7",
            "tenantId": "94b280022d0c4401bcf3b0ea85870519",
            "userId": "558057c4256545bd8a307c37464003c9",
            "name": "gcp-backend-file",
            "type": "gcp-file",
            "region": "<project_id>"
        }
    ],
    "next": 1
}
```
**Create a File share**

Example 1: Creating File Share for AWS Backend

POST http://192.168.20.162:8089/v1/94b280022d0c4401bcf3b0ea85870519/file/shares
Request:
```
{
    "name": "gcpfshim",
    "description": "GCP FileShare",
    "backendId": "5f66397740852a0001bcc3f7",
    "availabilityZone": "asia-east1-a",
    "size": 1099511627776,
    "type": "cloudFS",
    "tags": [
      {
        "key": "creator",
        "value": "himanshu"
      }
    ],
    "metadata": {
      "Tier": "STANDARD"
    }
}
```
Response:
```
{
    "id": "5f663ac22c7bc100019d2cd6",
    "createdAt": "2020-09-19T22:37:14",
    "updatedAt": "2020-09-19T22:37:14",
    "name": "gcpfshim",
    "description": "GCP FileShare",
    "tenantId": "94b280022d0c4401bcf3b0ea85870519",
    "userId": "558057c4256545bd8a307c37464003c9",
    "backendId": "5f66397740852a0001bcc3f7",
    "backend": "gcp-backend-file",
    "size": 1099511627776,
    "type": "cloudFS",
    "region": "<project_id>",
    "availabilityZone": "asia-east1-a",
    "status": "creating",
    "tags": [
        {
            "key": "creator",
            "value": "himanshu"
        }
    ],
    "metadata": {
        "fields": {
            "Tier": {
                "Kind": {
                    "StringValue": "STANDARD"
                }
            }
        }
    }
}
```
image
image

**Special notes for your reviewer**:
Since GET Fileshare API for GCP implementation is not included in this PR. Sync Metadata from cloud to DB will break.

### CODE REVIEW

File: contrib/datastore/file/gcp/gcp.go [hunk 1]
```diff
@@ -30,7 +44,44 @@ type GcpAdapter struct {
 }
 
 func (g GcpAdapter) CreateFileShare(ctx context.Context, fs *file.CreateFileShareRequest) (*file.CreateFileShareResponse, error) {
-	panic("implement me")
+	instanceName := fs.Fileshare.Name + "-instance"
```
Comment (kumarashit) [inline contrib/datastore/file/gcp/gcp.go:47]: Why to append "-instance" ? Does GCP expects the name to be suffixed with this?

File: contrib/datastore/file/gcp/gcp.go [hunk 2]
```diff
@@ -30,7 +44,44 @@ type GcpAdapter struct {
...
+		labels[tag.Key] = tag.Value
+	}
+
+	instance := &gcpfilev1.Instance{
+		Description: fs.Fileshare.Description,
+		Tier: fs.Fileshare.Metadata.Fields[Tier].GetStringValue(),
+		FileShares: []*gcpfilev1.FileShareConfig{
+			{
+				Name:       fs.Fileshare.Name,
+				CapacityGb: fs.Fileshare.Size / utils.GB_FACTOR,
```
Comment (kumarashit) [inline contrib/datastore/file/gcp/gcp.go:59]: Why do we expect the input to come in bytes? User can specify simply 1GB or 1 TB etc.

File: contrib/datastore/file/gcp/gcp.go [hunk 3]
```diff
@@ -30,7 +44,44 @@ type GcpAdapter struct {
...
+		Networks: []*gcpfilev1.NetworkConfig{
+			{
+				Network:         DefaultNetwork,
+				Modes:           []string{InternetProtocolModeIpv4},
+			},
+		},
+		Labels: labels,
+	}
+
+	log.Infof("Starting CreateInstance on cloud backend")
```
Comment (kumarashit) [inline contrib/datastore/file/gcp/gcp.go:71]: Redundant log message, next line is fine.

File: contrib/datastore/file/gcp/gcp.go (hunk 2 above)
Comment (himanshuvar) [reply contrib/datastore/file/gcp/gcp.go:59]: I didn't get the point for the input expectation in bytes and user specification? Where do you expect User simply specify GB or TB?
IMHO we should provide the basic storage unit i.e. byte across internal API calls & db persistence and let the respective backend decide to consume in their API specification format, some may consume in bytes, GB, TB etc.

File: contrib/datastore/file/gcp/gcp.go (hunk 1 above)
Comment (himanshuvar) [reply contrib/datastore/file/gcp/gcp.go:47]: No GCP doesn't expect that suffix, used this approach to get utilization of FileShare name from multi-cloud API itself to  provide GCP backend operation for Filestore Instance creation.
Any other suggestion?

File: contrib/datastore/file/gcp/gcp.go (hunk 3 above)
Comment (himanshuvar) [reply contrib/datastore/file/gcp/gcp.go:71]: First one is specifying the GCP backend operation. The next line to log the instance object.
I will update the log level to debug for next line.

File: contrib/datastore/file/gcp/gcp.go (hunk 1 above)
Comment (kumarashit) [reply contrib/datastore/file/gcp/gcp.go:47]: Leave the name as provided by user. Please don’t add suffix.

File: contrib/datastore/file/gcp/gcp.go (hunk 2 above)
Comment (kumarashit) [reply contrib/datastore/file/gcp/gcp.go:59]: Right. Let’s keep it this way. So expectation is that API consumer will do conversions

File: contrib/datastore/file/gcp/gcp.go (hunk 3 above)
Comment (kumarashit) [reply contrib/datastore/file/gcp/gcp.go:71]: Ok

**Review by kumarashit — COMMENTED** [review]
Please fix fs naming conventions

File: contrib/datastore/file/gcp/gcp.go (hunk 1 above)
Comment (himanshuvar) [reply contrib/datastore/file/gcp/gcp.go:47]: GCP Cloud Backend API needs Instance Id and FileShare Name. Just to distinguish instance & fileshare. I used this prefix. I am not taking instance as a separate input from User. Just tried to combine the logic from SODA multi-cloud for GCP backend operation.
Please refer following snapshot.
image
image

**Comment by himanshuvar** [comment]
> 
> 
> Please fix fs naming conventions

If we needs to take the instance name from User input. I can add instance id to metadata. What do you say?

File: contrib/datastore/file/gcp/gcp.go (hunk 1 above)
Comment (kumarashit) [reply contrib/datastore/file/gcp/gcp.go:47]: ok

**Review by kumarashit — APPROVED** [review]
LGTM

**Review by skdwriting — APPROVED** [review]
LGTM
